name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk
        uses: snyk/actions/setup@v1
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}

      - name: Run Security Scan
        run: snyk test
